Repository OS-ABC/Kcoin-Golang, pull requests merged in 2019-12, with the labels that each got.

#162 完成本周任务getAllJoinedProjects.go
  src/models/getAllJoinedProjects.go
Labels: TestResultNeeded, webserver

#161 查询所有项目时，添加了查询每个项目中的成员列表
  src/models/k_project.go
Labels: TestResultNeeded, webserver

#198 fix #183 & 188 增加工作列表页面和项目贡献度评定规则
  src/controllers/projectMemberWork.go
  src/routers/router.go
  src/views/projectInfo.html
  src/views/projectMemberList.html
  src/views/projectMemberWork.html
Labels: front-end

#197 fix #185
  src/static/css/capitalInjection.css
  src/static/css/import.css
  src/static/css/join.css
  src/static/css/loginJoin.css
  src/static/css/personal.css
  src/static/css/personalPage.css
  src/static/css/personalProjects.css
  src/static/css/platformAdmin.css
  src/static/css/platformAdminTopNav.css
  src/static/css/project.css
  src/static/css/projectFunding.css
  src/static/css/projectNotice.css
  src/static/css/projectTopNav.css
  src/views/capitalInjection.html
  src/views/ccSearchPage.html
  src/views/import.tpl
  src/views/join.html
  src/views/leftNav.html
  src/views/login.html
  src/views/personalPage.html
  src/views/personalProjects.html
  src/views/platformAdminTopNav.html
  src/views/platformInformation.html
  src/views/projectFunding.html
  src/views/projectInfo.html
  src/views/projectMemberList.html
  src/views/projectNotice.html
  src/views/projectSetting.html
  src/views/projectTopNav.html
Labels: front-end

#196 fix #175 更新github标识name to id
  src/controllers/authorize.go
  src/controllers/github_helper.go
  src/models/k_user.go
Labels: webserver

#195 fixes #177 实现解析url函数
  src/models/getContributors.go
  src/models/getProgramInfo.go
  src/models/parseGithubHTTPSUrl.go
Labels: help wanted, webserver

#193 fixed#184，实现页面跳转和用户权限验证
  src/static/js/import.js
  src/views/personalProjects.html
Labels: front-end

#207 fix issue 131 CheckGithubRepoUrl, 待review
  src/controllers/github_helper.go
Labels: webserver

#201 fix issue#181 为部分函数增加测试用例
  src/models/getContributors.go
  src/tests/default_test.go
  src/tests/models_test.go
Labels: webserver

#190 fixes #182 添加textfield和其session功能
  src/conf/app.conf
  src/controllers/import.go
  src/controllers/personalProjects.go
  src/controllers/projectSetting.go
  src/views/personalProjects.html
  src/views/projectSetting.html
Labels: front-end

#213 修改了个人中心获取头像和用户名的方式
  src/controllers/personalPage.go
  src/controllers/personalProjects.go
Labels: front-end

#217 修改了首页平台管理的跳转，在平台管理页面加入了返回首页的跳转
  src/static/css/platformAdmin.css
  src/views/homePage.tpl
  src/views/platformAdminTopNav.html
Labels: front-end

#240 修复了首页项目列表不显示的bug
  src/models/k_project.go
Labels: bug
